{% set version = "0.3.0" %}

package:
  name: xarray-simlab
  version: {{ version }}

source:
  fn: xarray-simlab-{{ version }}.tar.gz
  url: https://github.com/benbovy/xarray-simlab/archive/{{ version }}.tar.gz
  sha256: b94454eb963c70f5767de93ff73d2c912924d84d5851ef1a94953db9f9df9257

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - attrs >=18.1.0
    - numpy
    - xarray >=0.10.0,<0.14.1

test:
  imports:
    - xsimlab

about:
  home: https://github.com/benbovy/xarray-simlab
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'xarray extension for computer model simulations.'

extra:
  recipe-maintainers:
    - benbovy
