travis:
  secure:
    BINSTAR_TOKEN: kO9Y2rDPgVuUoDPyEU505GszN4/THJuJpdDXBTHDza9fIq75rBR59J9e9KEcJbjG7734nHyPMQHKqMnxhF6xodLGjw9m8S+XRgMPSv7v1De1JdlTEbtL+XdCja0YdknugNjUf1LtHucfDdO9XHiZHmaHx3x8W5TOFAnYW5VgTtP5OWogkF1Qv4Xg/XKB1EbLAVlMCEMdC2xXt2bs9GMxpBYTNnuDEzLy4RiYYRDc0cVxjhEN4NGmj/Ju8yfN5V4WkVYuPY0XX7BSmQnN4aYK+zITEkdZHPGpPREAs51bzlilQ/H8o/5fQ9lwlNQRSeYBBNN0arO1wCrqpUMjDooyA0gi+JgEUqeUR+BTnBlcV/T07WYlBXoBAvxEI2LYngSfGfTgcQxeDrSgI0IrEJ/fRGzbrU3sHOUebhBIIydJ660HqJ4TJ+FwwhS9Wu0OQCseqz6XCC0ZCrzqQdNu3HEo8Vk/0oVu7G5EdydB+jKHjOQxCuY39Zzzi2bLCX2rhJdg2Gk27SZMOgb35V9+54TCHemOqoP2GUL8y4JA1ERDfTwuotDBpxb28l24pIbwCDHbt1N94EuQDqMFPGp54TNy8cnfhNb9xnrpE/5L1van9rQMUeqd3wRvhw7OpV2rGJpepYgJvGScSn/3XOmt4UWZBFj72JsRH01U2UZKZxp7brI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
