travis:
  secure:
    BINSTAR_TOKEN: nn5vYJex5escIi3Rt5N2zKfJjqtHuE2zLQ8RFp+IeGwEmMXgx5VSNnO3jzif47sO2ZtIWg4b5SMWn3IEHl4Pm/Wgaq1o3A5ehPk4RoxcL23iwYlI8sXPcmqtVimMWkIVbBf6AKWYFmB2EAxR+OyKqriKk7ChksujQEiK8Br4nY1RsB4GNlGP1dDi72rm8t6e3Qeqxbv+sXAUMS4f5C3uS8HL1Tf6P3I4HhVyKRJAOKeoBZHg5qfpymL6f0bNwI9bbztN7JTwGyldZk01PRHLkb9ZxzwyWOX75kVYB8tfevSFOcJO8nun7hC66kVl6rhiGfS2jxflWLdKPTlt6MwUntpno63l9LMEef75+cQsHyjkACWmo4IQWQ5lcOZDy9PfOFfKqaUyoqokTQrTkmVpVX3yGHTPQS1zEijBb/XRej4Jgnei8aFsY1xVdWkvBfVku54aHGPsKwiOxdFyEL+BxYhjWWlfUIi8JDANUNMLdKG0SxTc8W27XS1NKterO1WDKEnD2cCPlqtmAvSWjkMidDrXffwGQMdswwlOU87bmrDB87zi909Er7izdut8bj3dHE6XQJ8NlBV/0uM0HV5XRrshZnkBVrSb7z4fsSOnpD+GkywfMbbjOYEgX5M/9zIRmRV2e6AloGDTiJLUxO1LeKYNN+F/RN1mHhMf1sTICls=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
